#ifndef BINSEQ_H
#define BINSEQ_H

/* This file was automatically generated by cbindgen. DO NOT EDIT. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Creates a new empty record for reuse
 *
 * # Safety
 * The caller must free the record with binseq_record_free when done
 */
struct BinseqRecord *binseq_record_new(void);

/**
 * Creates a new decoding context with pre-allocated buffers
 *
 * # Safety
 * The caller must free the context with binseq_context_free when done
 */
struct BinseqContext *binseq_context_new(void);

/**
 * Frees a context
 */
void binseq_context_free(struct BinseqContext *context);

/**
 * Opens a binseq file and returns a reader
 *
 * # Safety
 * The caller must free the reader with binseq_reader_close when done
 */
struct BinseqReader *binseq_reader_open(const char *path);

/**
 * Closes and frees a binseq reader
 */
void binseq_reader_close(struct BinseqReader *reader);

/**
 * Returns the number of records in the file
 */
uintptr_t binseq_reader_num_records(const struct BinseqReader *reader);

/**
 * Returns the primary sequence length
 */
uint32_t binseq_reader_slen(const struct BinseqReader *reader);

/**
 * Returns the paired sequence length
 */
uint32_t binseq_reader_xlen(const struct BinseqReader *reader);

/**
 * Gets a record by index and stores it in a reusable record container
 * Returns true if successful, false on error
 *
 * # Safety
 * The record container must be created with binseq_record_new
 */
bool binseq_reader_get_record(const struct BinseqReader *reader,
                              uintptr_t idx,
                              struct BinseqRecord *record_container);

/**
 * Clear a record container (does not free it)
 */
void binseq_record_clear(struct BinseqRecord *record);

/**
 * Check if a record container is empty (contains no valid record)
 */
bool binseq_record_is_empty(const struct BinseqRecord *record);

/**
 * Frees a record container
 */
void binseq_record_free(struct BinseqRecord *record);

/**
 * Gets the flag for a record
 */
uint64_t binseq_record_flag(const struct BinseqRecord *record);

/**
 * Checks if a record is paired
 */
bool binseq_record_is_paired(const struct BinseqRecord *record);

/**
 * Decodes the primary sequence into the context's internal buffer
 * Returns the sequence length
 */
uintptr_t binseq_record_decode_primary(const struct BinseqRecord *record,
                                       struct BinseqContext *context);

/**
 * Decodes the extended sequence into the context's internal buffer
 * Returns the sequence length
 */
uintptr_t binseq_record_decode_extended(const struct BinseqRecord *record,
                                        struct BinseqContext *context);

/**
 * Gets a pointer to the primary sequence buffer in the context
 * The pointer is only valid until the next call to any decode function
 */
const char *binseq_context_primary_ptr(const struct BinseqContext *context);

/**
 * Gets the length of the primary sequence buffer in the context
 */
uintptr_t binseq_context_primary_len(const struct BinseqContext *context);

/**
 * Gets a pointer to the extended sequence buffer in the context
 * The pointer is only valid until the next call to any decode function
 */
const char *binseq_context_extended_ptr(const struct BinseqContext *context);

/**
 * Gets the length of the extended sequence buffer in the context
 */
uintptr_t binseq_context_extended_len(const struct BinseqContext *context);

/**
 * Copies the primary sequence to a user-provided buffer
 * Returns the number of bytes copied
 */
uintptr_t binseq_context_copy_primary(const struct BinseqContext *context,
                                      char *buffer,
                                      uintptr_t buffer_size);

/**
 * Copies the extended sequence to a user-provided buffer
 * Returns the number of bytes copied
 */
uintptr_t binseq_context_copy_extended(const struct BinseqContext *context,
                                       char *buffer,
                                       uintptr_t buffer_size);

/**
 * Gets the last error message
 */
const char *binseq_last_error(void);

#endif  /* BINSEQ_H */
